/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class PrimeSieveTest {
    @Test public void testSomeLibraryMethod() {
        PrimeSieve primeSieve = new PrimeSieve();
        assertTrue("someLibraryMethod should return 'true'", primeSieve.numPrimes3(200) == 46);

    }
}
